name: Run SEQ Simulation
on: [push, workflow_dispatch]
jobs:
  sim:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: python src/sim_runner.py
    - uses: actions/upload-artifact@v4
      with:
        name: seq-results
        path: outputs/
