name: Run SEQ Simulation

on:
  push:
  workflow_dispatch:

jobs:
  sim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run simulation
        run: |
          python src/sim_runner.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: seq-results
          path: |
            outputs/plot.png
            outputs/metrics.json
            outputs/seq_log.csv
            outputs/shard.json

